### ISSUE TITLE
Left panel: Recategorized entities are staying in the list to which they were originally assigned.

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#55]
This is after clicking off the category and back onto it to see if that would fix it.

![image.png](https://images.zenhubusercontent.com/5a60ec3a4b5806bc2bc34e2e/b0481884-d4b5-4d33-a30c-3f793b7ade63)

**Comment by Thaerious** [comment]
This is fixed in 0.8.5.  Note I have temporarily disabled cut-paste of values.  This fix may cascade small bugs to other parts of the program.

**Comment by ilovan** [comment]
Still an issue:
File: https://www.dropbox.com/s/47obkh11xv1m8td/NERVE%20-%20ultra-basic%20test%20-%20TEI.xml?dl=0
"NER & link" applied


Indiana  - changed from place to title and linked to a wikidata URI:

![image](https://user-images.githubusercontent.com/6600070/41046562-e1a0a270-6967-11e8-8954-ce69a259ef62.png)

**Comment by ilovan** [comment]
Seems to be fixed now.
