### ISSUE TITLE
Ref attributes not populated in processed docs

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#61]
Before and after files:
https://www.dropbox.com/s/gsc670mjb18a1rr/NERVE%20-%20ultra-basic%20test%20-%20TEI%20%285%29.xml?dl=0
https://www.dropbox.com/s/zpw4czrckjyl1u2/NERVE%20-%20ultra-basic%20test%20-%20TEI.xml?dl=0

**Comment by Thaerious** [comment]
Fixed in 0.8.5 
Is causing other issues as it was caused by a fix to something else.

**Comment by ilovan** [comment]
Still not fixed:
result of https://www.dropbox.com/s/47obkh11xv1m8td/NERVE%20-%20ultra-basic%20test%20-%20TEI.xml?dl=0 run through "NER & link":


![image](https://user-images.githubusercontent.com/6600070/41046271-5d0225ca-6967-11e8-9a53-4736248cf0f1.png)

**Comment by SusanBrown** [comment]
regarding opening linking and tagging of entities that are already in whitelist

**Comment by ilovan** [comment]
fixed
